### ISSUE TITLE
Parse config with custom logic defined outside of module export

### ISSUE THREAD

**Issue by thien-do** [thien-do/typed.tw#17]
Test case: https://gist.github.com/dvkndn/ab434cae1ee42528723f05159172f69f

As far as I remember it's because typed.tw only parses the part inside module.export.. which is so wrong..

**Comment by dvkndn** [comment]
This shouldn't even be an error if the processing happen locally I guess

**Comment by dvkndn** [comment]
workaround https://github.com/dvkndn/otf.show/blob/master/src/styles/utilities.config.js#L23-L27
