### ISSUE TITLE
Whole and rational numbers result in the same method name

### ISSUE THREAD

**Issue by joprice** [thien-do/typed.tw#27]
Duplicate method names are generated for classes like `md:w-2/4` and `md:w-24`. The method for both is `mdW24`.

**Comment by dvkndn** [comment]
Hm weird I thought I fixed it.. let me check again! Thank you

**Comment by joprice** [comment]
I'm using an empty config if that helps.

**Comment by snowfrogdev** [comment]
Also experiencing this problem.

**Comment by thien-do** [comment]
hi @snowfrogdev @joprice terribly sorry but I'm not currently actively working on this 🙏 I'll try to fix it but can't guarantee :D
